#TOML doc :D

# AsudServ@gmail.com - mail  H49qFgUDTzSUQFYmoVwf - pass

logger_path = "logfiles/custLog"
ginLog_path = "logfiles/ginLog"
static_path = "resources/static"
web_path = "resources/web"
free_path = "resources/free"
ssl_path = "ssl"
server_ip = ":80"   #ip + port основного сервера
server_exchange = ":8085" #ip + port сервера обмена

#настройка подключения к тсп серверу обемена командами
[tcpServer]
tcpServerAddress = "192.168.115.115"
portState = "2002"
portArmCommand = "2001"
portChangeProtocol = "2003"
portDkConn = "2004"
portGPRS = "1093"
sendGPRS = false

#настройки для постгреса
[database]
db_name = "agserv"
db_password = "162747"
db_user = "postgres"
db_type = "postgres"
db_host = "192.168.115.115"
db_port = "5432"
db_SetMaxOpenConst = 50
db_SetMaxIdleConst = 10
